import Head from "next/head";
import Navbar from "../components/Navbar";
import Image from "next/image";
import {
  CircularSupplyChain,
  NonFungibleThings,
  CityverseHub,
  SmartTags,
  WelcomeToNexity,
  InvestorRelations,
  GreenPoints,
  BuilderStudios,
} from "../images/HomeImages/HomeImagesExport";

import Footer from "../components/Footer";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-row-8 grid-col-2 gap-1">
        {/* //******************* Welcome page ********************************** */}

        <div className="col-span-2 h-screen text-white flex items-center flex-col relative overflow-hidden justify-center">
          <Navbar />
          <video
            autoPlay
            muted
            loop
            className="object-cover absolute top-0 left-0 -z-10 h-full w-full"
          >
            <source src="/bg-video.mp4" type="video/mp4" />
          </video>
          <div
            data-aos="fade-up"
            className="text-center w-[55vw] flex flex-col "
          >
            <div className="uppercase font-bold text-2xl text-gray-300 font-mono">
              Welcome To
            </div>
            <div className="lg:text-8xl font-bold mt-16 xs:text-xl sm:text-2xl md:text-5xl text-transparent bg-clip-text bg-gradient-to-r from-sky-500 to-teal-200">
              A Circular World on the Blockchain
            </div>
          </div>
        </div>

        {/* //******************* Circular Supply Chain ************************* */}

        <div className="col-span-2  bg-[#1e1e3a] text-white h-[75vh] flex items-center justify-center relative">
          <div className="rounded-2xl h-[50vh] w-[70vh] bg-gradient-radial from-[#1159aa] to-[#1e1e3a] blur-3xl absolute left-[calc(100vw-30)] z-0"></div>
          <div
            data-aos="fade-up"
            className="flex justify-center items-center z-10"
          >
            <Image src={CircularSupplyChain} />
            <div className="ml-24 text-center">
              <div className="text-6xl font-extrabold ">
                Circular <br /> Supply Chain
              </div>
              <div className="text-2xl mt-8  ">
                Work without waste. <br /> Redefining the way we do business
                together.
              </div>
              <div className="text-xl mt-8 text-blue-500">Explore </div>
            </div>
          </div>
        </div>

        {/* //******************* Non-Fungible Things *************************** */}

        <div className="col-span-2  bg-[#11111f] text-white h-[75vh] flex items-center justify-center relative">
          <div className="rounded-2xl h-[50vh] w-[70vh] bg-gradient-radial from-[#3d2483] to-[#11111f] blur-3xl absolute left-[calc(100vw-30)] z-0"></div>
          <div
            data-aos="fade-up"
            className="flex justify-center items-center z-10"
          >
            <div className="mr-24 text-center">
              <div className="text-6xl font-extrabold ">
                Non-Fungible
                <br /> Things
              </div>
              <div className="text-2xl mt-8  ">
                User-friendly. Enterprise-ready.
              </div>
              <div className="text-xl mt-8 text-blue-500">Enter Now </div>
            </div>
            <Image src={NonFungibleThings} width={550} height={450} />
          </div>
        </div>

        {/* //******************* Cityverse Hub *************************** */}

        <div className="col-span-2  bg-[#14033a] text-white h-[75vh] flex  items-center justify-center relative">
          <div className="rounded-2xl h-[50vh] w-[70vh] bg-gradient-radial from-[#24267e] to-[#14033a] blur-3xl absolute left-[calc(100vw-30)] z-0"></div>
          <div
            data-aos="fade-up"
            className="flex justify-center items-center z-10 flex-col"
          >
            <div className="text-center">
              <div className="text-6xl font-extrabold ">Cityverse Hub</div>
              <div className="text-2xl mt-8  ">
                Interactive. Augmented.
                <br />
                The future of shopping is here.
              </div>
              <div className="text-xl mt-8 text-blue-500 mb-12">Discover </div>
            </div>
            <Image src={CityverseHub} width={650} height={300} />
          </div>
        </div>

        {/* //*******************Smart Tags *************************** */}

        <div className="col-span-2  bg-[#3a0173] text-white h-[75vh] flex items-center justify-center relative">
          <div className="rounded-2xl h-[50vh] w-[70vh] bg-gradient-radial from-[#896cda] to-[#3a0173] blur-3xl absolute left-[calc(100vw-30)] z-0"></div>
          <div
            data-aos="fade-up"
            className=" flex justify-center items-center z-10"
          >
            <Image src={SmartTags} />
            <div className="ml-24 text-center">
              <div className="text-6xl font-extrabold ">Smart Tags</div>
              <div className="text-2xl mt-8  ">
                Brand DNA. Certified. <br />
                An ultra-personal ownership experience.
              </div>
              <div className="text-xl mt-8 text-blue-500">Explore </div>
            </div>
          </div>
        </div>

        {/* //*******************Welcome to nexity *************************** */}

        <div className=" flex-auto bg-[#1b062c] text-white h-[75vh] flex items-center justify-center relative">
          <div
            data-aos="fade-up"
            className="flex flex-col justify-center items-center z-10"
          >
            <div className=" text-center">
              <div className="text-6xl font-extrabold ">Welcome to Nexity</div>
              <div className="text-2xl mt-8  ">
                Circular. Digital. <br />
                We're building a new global economy.
              </div>
              <div className="text-xl mt-8 mb-12 text-blue-500">
                Find out how{" "}
              </div>
            </div>
            <Image src={WelcomeToNexity} height={320} width={500} />
          </div>
        </div>

        {/* //*******************Investor Relations*************************** */}

        <div className=" flex-auto  bg-[#030822] text-white h-[75vh] flex items-center justify-center relative">
          <di
            data-aos="fade-up"
            data-aos-delay="500"
            className=" flex flex-col justify-center items-center z-10"
          >
            <div className=" text-center">
              <div className="text-6xl font-extrabold  text-sky-400">
                Investor Relations
              </div>
              <div className="text-2xl mt-8  ">
                Co-own. Advance. Contribute to something. <br />
                larger than yourself.
              </div>
              <div className="text-xl mt-8 mb-12 text-blue-500">
                Get Involved
              </div>
            </div>
            <Image src={InvestorRelations} height={320} width={250} />
          </di>
        </div>
        {/* //*******************Green Points*************************** */}

        <div className=" flex-auto bg-[#041a20] text-white h-[75vh] flex items-center justify-center relative">
          <div
            data-aos="fade-up"
            className="  flex flex-col justify-center items-center z-10"
          >
            <div className=" text-center">
              <div className="text-6xl font-extrabold text-teal-300">
                Green Points
              </div>
              <div className="text-2xl mt-8  ">Do more. Earn more.</div>
              <div className="text-xl mt-8 mb-12 text-blue-500">Farm now</div>
            </div>
            <Image src={GreenPoints} height={300} width={430} />
          </div>
        </div>

        {/* //*******************Builder Studios*************************** */}

        <div className=" flex-auto  bg-[#123d3d] text-white h-[75vh] flex items-center justify-center relative">
          <di
            data-aos="fade-up"
            data-aos-delay="500"
            className=" flex flex-col justify-center items-center z-10"
          >
            <div className=" text-center">
              <div className="text-6xl font-extrabold ">Builder Studios</div>
              <div className="text-2xl mt-8  ">Co-create. Grow faster.</div>
              <div className="text-xl mt-8 mb-12 text-blue-500">
                Get started
              </div>
            </div>
            <Image src={BuilderStudios} height={300} width={250} />
          </di>
        </div>

        {/* //*******************Footer Studios*************************** */}
        <Footer />
      </div>
    </>
  );
}
